#' Get the PACTA manual sector override table
#'
#' @param conn database connection
#'
#' @return A tibble properly prepared to be saved as the
#'   `factset_manual_pacta_sector_override.rds` output file
#'
#' @export

get_manual_sector_override <- function(conn) {
  # build connection to database ---------------------------------------------

  logger::log_debug("Extracting manual PACTA sector override table.")


  # factset_entity_id -----------------------------------------------
  logger::log_trace("Accessing entity information.")
  sym_entity <- dplyr::tbl(conn, "sym_v1_sym_entity")

  logger::log_trace("Preparing company names.")
  company_names <- pacta_override_mapping[["entity_proper_name"]]

  factset_entity_info <- sym_entity %>%
    dplyr::select(
      dplyr::all_of(
        c(
          "factset_entity_id",
          "entity_proper_name"
        )
      )
    ) %>%
    dplyr::filter(.data[["entity_proper_name"]] %in% company_names)

  # merge and collect --------------------------------------------------------

  logger::log_trace("Downloading entity information for override companies.")
  factset_entity_info <- dplyr::collect(factset_entity_info)
  logger::log_trace("Download complete.")

  logger::log_trace("Adding PACTA sector overrides.")
  pacta_sector_override <- dplyr::full_join(
    x = factset_entity_info,
    y = pacta_override_mapping,
    by = dplyr::join_by("entity_proper_name")
  )

  incomplete_cases <- dplyr::filter(
    pacta_sector_override,
    !complete.cases(pacta_sector_override)
  )

  if (nrow(incomplete_cases) > 0L) {
    # converting to formatter sprintf to deal with strings that break {glue}
    old_formatter <- logger::log_formatter()
    logger::log_formatter(logger::formatter_sprintf)
    logger::log_warn(
      "Company could not be matched by name in FactSet database: %s",
      incomplete_cases[["entity_proper_name"]]
    )
    logger::log_formatter(old_formatter)
  }

  # return prepared data -----------------------------------------------------
  return(pacta_sector_override)
}

pacta_override_mapping <- tibble::tribble(
  ~entity_proper_name, ~pacta_sector,
  "St. Marys Cement Inc. (Canada)", "Cement",
  "Volkswagen Group of America Finance LLC", "Other",
  "City of Dallas (Texas)", "Other",
  "Toyota Motor Credit Corp.", "Other",
  "CNOOC Finance (2012) Ltd.", "Oil&Gas",
  "American Airlines 2016-3 Pass Through Trust", "Aviation",
  "Glencore Finance (Canada) ltd.", "Coal",
  "Pemex Project Funding Master Trust", "Oil&Gas",
  "Ford Credit Canada Co.", "Other",
  "Ford Motor Credit Co. LLC", "Other",
  "BP Capital Markets PLC", "Oil&Gas",
  "General Motors Financial Co., Inc.", "Other",
  "VW Credit Canada, Inc.", "Other",
  "United Airlines 1995-A Pass Through Trusts", "Aviation",
  "Woodside Finance Ltd.", "Oil&Gas",
  "Cnooc Finance (2015) Australia Pty Ltd.", "Oil&Gas",
  "Empresas P√∫blicas de Medell√≠n ESP", "Power",
  "Sinopec Group Overseas Development (2012) Ltd.", "Oil&Gas",
  "GTL Trade Finance, Inc.", "Steel",
  "ENEL Finance International NV", "Power",
  "Genel Energy Finance Plc", "Oil&Gas",
  "State Grid Corp. of China", "Power",
  "The Bank of New York Mellon Corp.", "Other",
  "Volkswagen Bank GmbH", "Other",
  "CLP Power Hong Kong Financing Ltd.", "Power",
  "BMW International Investment BV", "Other",
  "Volvo Treasury AB", "Other",
  "China Petrochemical Corp.", "Oil&Gas",
  "LUKOIL Securities BV", "Oil&Gas",
  "BMW Finance NV", "Other",
  "ESB Finance DAC", "Power",
  "National Rural Utilities Cooperative Finance Corp.", "Power",
  "CSN Islands XII Corp.", "Steel",
  "GOL Finance Ltd.", "Aviation",
  "American Airlines 2001-1 Pass ThroughTrust", "Aviation",
  "American Airlines 2016-2B Pass Through Trust", "Aviation",
  "MMK International Capital DAC", "Steel",
  "General Electric Capital Corp.", "Power",
  "Delta Air Lines Pass Through 2007-1", "Aviation",
  "CNPC (HK) Overseas Capital Ltd.", "Oil&Gas",
  "Sinopec Group Overseas Development (2017) Ltd.", "Oil&Gas",
  "NextEra Energy Capital Holdings, Inc.", "Power",
  "ENBW International Finance BV", "Power",
  "Total Capital International SA", "Oil&Gas",
  "EDP Finance BV", "Power",
  "Volkswagen Financial Services Australia Pty Ltd.", "Other",
  "Naturgy Finance BV", "Power",
  "TNB Global Ventures Capital Bhd.", "Power",
  "Gaz Capital SA", "Oil&Gas",
  "BHP Billiton Finance Ltd.", "Coal",
  "General Electric Co.", "Power",
  "Toyota Finance Australia Ltd.", "Other",
  "British Airways Pass Through Trust 2018-1AA", "Aviation",
  "State Grid Overseas Investment (2013) Ltd.", "Power",
  "Phillips Petroleum Co.", "Oil&Gas",
  "Petronas Capital Ltd.", "Oil&Gas",
  "Mercedes-Benz Finance North America LLC", "Other",
  "Companhia Brasileira de Alum√≠nio", "Steel",
  "CNOOC Finance (2003) Ltd.", "Oil&Gas",
  "CalEnergy Co., Inc.", "Power",
  "Niagara Mohawk Power Corp.", "Power",
  "Petrobras Global Finance BV", "Oil&Gas",
  "Government of Gabon", "Other",
  "GE Capital Funding LLC", "Power",
  "San Diego Gas & Electric Co.", "Power",
  "CRH America Finance, Inc.", "Cement",
  "NAS Pass Through Trust 2016-1B", "Aviation",
  "Toyota Motor Finance Netherlands BV", "Other",
  "BMW US Capital LLC", "Other",
  "Volkswagen International Finance NV", "Other",
  "TNB Western Energy Bhd.", "Power",
  "Chongqing Energy Investment Group Co., Ltd.", "Coal",
  "China Southern Power Grid Co., Ltd.", "Power",
  "Mercedes-Benz International Finance BV", "Other",
  "Polski Koncern Naftowy ORLEN SA", "Oil&Gas",
  "Reliance Industries Ltd.", "Oil&Gas",
  "LATAM Finance Ltd.", "Aviation",
  "UGI Utilities, Inc.", "Power",
  "Tosco Corp.", "Oil&Gas",
  "British Airways Pass Through Trust Series 2013-1", "Aviation",
  "PACCAR Financial Corp.", "Other",
  "BG Energy Capital Plc", "Oil&Gas",
  "RCI Banque SA", "Other",
  "CRH Finance UK Plc", "Cement",
  "Bharat Petroleum Corp. Ltd.", "Oil&Gas",
  "CGNPC International Ltd.", "Power",
  "ABJA Investment Co. Pte Ltd.", "Steel",
  "Manjung Island Energy Bhd.", "Power",
  "Volkswagen Financial Services AG", "Other",
  "Titan Global Finance Plc", "Cement",
  "American Honda Finance Corp.", "Other",
  "Northern Electric Finance Plc", "Power",
  "Shell International Finance BV", "Oil&Gas",
  "US Airways, Inc.", "Aviation",
  "Glencore Funding LLC", "Coal",
  "Petroleos Del Peru - Petroperu SA", "Oil&Gas",
  "State of Alaska", "Other",
  "Conoco, Inc.", "Oil&Gas",
  "Novatek Finance DAC", "Oil&Gas",
  "BP Capital Markets America, Inc.", "Oil&Gas",
  "Three Gorges Finance I (Cayman Islands) Ltd.", "Power",
  "State Grid Overseas Investment (2014) Ltd.", "Power",
  "BHP Billiton Finance (USA) Ltd.", "Coal",
  "GPN Capital SA", "Oil&Gas",
  "American Airlines 2019-1 Through Trust", "Aviation",
  "British Airways Pass Through Trust 2019-1", "Aviation",
  "Steel Capital SA", "Steel",
  "Glencore Finance (Europe) Ltd.", "Coal",
  "Saudi Electricity Global Sukuk Co. - 4", "Power",
  "Mercedes-Benz Australia/Pacific Pty Ltd.", "Other", # nolint: nonportable_path_linter
  "Volkswagen Financial Services NV", "Other",
  "Voyage Bonds Ltd.", "Steel",
  "Genneia SA", "Power",
  "CNX Resources Corp.", "Oil&Gas",
  "GMF Floorplan Owner Revolving Trust 2018-4 Ltd.", "Other",
  "CNOOC Curtis Funding No. 1 Pty Ltd.", "Oil&Gas",
  "Nissan Motor Acceptance Co.", "Other",
  "Anadarko Finance Co.", "Oil&Gas",
  "Baltimore Gas & Electric Co.", "Power",
  "Instituto Costarricense de Electricidad", "Power",
  "General Motors Financial of Canada Ltd.", "Other",
  "Sinopec Group Overseas Development (2013) Ltd.", "Oil&Gas",
  "State Development & Investment Corp., Ltd.", "Power",
  "Equatorial Transmissora 8 Spe SA", "Power",
  "GIE PSA Tresorerie", "Other",
  "LUKOIL International Finance BV", "Oil&Gas",
  "Toyota Finance New Zealand Ltd.", "Other",
  "America West Airlines 2001-1", "Aviation",
  "Devon Financing Corp. ULC", "Oil&Gas",
  "Toyota Credit Canada, Inc.", "Other",
  "RGS (AEGCO) Funding Corp.", "Power",
  "United Airlines Pass Through Trust Series 2014-1", "Aviation",
  "Emerson Electric Co.", "Power",
  "WPD Holdings UK", "Power",
  "Banque PSA Finance SA", "Other",
  "United Airlines Pass Through Trust Series 2016-2", "Aviation",
  "Sinopec Group Overseas Development Ltd.", "Oil&Gas",
  "Canadian Utilities Ltd.", "Power",
  "GE Capital Australia Funding Pty Ltd.", "Power",
  "innogy Finance BV", "Power",
  "CITIC Ltd.", "Power",
  "GE Capital UK Funding Unlimited Co.", "Power",
  "GE Capital European Funding Unlimited Co.", "Power",
  "Kimanis Power Sdn. Bhd.", "Power",
  "Outokumpu Oyj", "Steel",
  "American Airlines 2011-2 Pass Through Trust", "Aviation",
  "Sinopec Group Overseas Development (2018) Ltd.", "Oil&Gas",
  "Sinopec Group Overseas Development (2016) Ltd.", "Oil&Gas",
  "Banco BTG Pactual SA (Grand Cayman Branch)", "Oil&Gas",
  "Indika Energy Capital III Pte Ltd.", "Coal",
  "United Airlines 2016-1 Class B Pass Thru Trust", "Aviation",
  "County of Dallas (Texas)", "Aviation",
  "Northwest Airlines Pass Through Trusts (NWA) 2002-1", "Aviation",
  "ENEL Finance International SA", "Power",
  "Ford Holdings, Inc.", "Other",
  "Susa Partnership LP", "Power",
  "Mercedes-Benz Finance Canada, Inc.", "Other",
  "BMW Canada, Inc.", "Other",
  "Origin Energy Finance Ltd.", "Power",
  "Energa Finance AB", "Power",
  "E.ON International Finance BV", "Power",
  "Alliant Energy Finance LLC", "Power",
  "United Airlines Pass Through Trust Series 2015-1", "Aviation",
  "Saudi Electricity Global Sukuk Co. - 3", "Power",
  "Continental Airlines Pass Through Certificates Ser 2012-2", "Aviation",
  "Holcim Finance (Luxembourg) SA", "Cement",
  "Abu Dhabi National Energy Co. PJSC", "Power",
  "China Huaneng Group Treasury Management (Hong Kong) Ltd.", "Power",
  "Hrvatska Elektroprivreda dd", "Power",
  "GE Capital International Funding Co.", "Power",
  "RGS I&M Funding Corp.", "Power",
  "Honda Canada Finance, Inc.", "Other",
  "US Airways 2013-1 Pass Through Trust", "Aviation",
  "China Clean Energy Development Ltd.", "Power",
  "Gusap III LP", "Steel",
  "PE Environmental Funding LLC", "Power",
  "Air Canada 2013-1 Pass Through Trust", "Aviation",
  "Sinopec Group Overseas Development (2014) Ltd.", "Oil&Gas",
  "United Airlines Pass Through Certificates Series 2019-1", "Aviation",
  "KeySpan Corp.", "Power",
  "NAS Pass Through Trust 2016-1A", "Aviation",
  "PPL Capital Funding, Inc.", "Power",
  "Holcim Capital Corp. Ltd.", "Cement",
  "SCE Trust V", "Power",
  "Gaz Finance Plc", "Oil&Gas",
  "American President Cos. Ltd.", "Shipping",
  "Continental Airlines Pass Through Certificates Series 2001-1", "Aviation",
  "CNOOC Finance (2011) Ltd.", "Oil&Gas",
  "American Airlines 2017-1 Pass Through Trust", "Aviation",
  "United Airlines Pass Through Certificate Series 2019-2", "Aviation",
  "Hilcorp Energy I LP", "Oil&Gas",
  "Mercedes-Benz Finance Co. Ltd.", "Other",
  "Nacional Financiera SNC", "Aviation",
  "AES Andres BV", "Power",
  "Delta Air Lines 2002-1", "Aviation",
  "American Airlines 2013-1A Pass Through Trust", "Aviation",
  "Vistra Operations Co. LLC", "Power",
  "Capex SA", "Power",
  "SCE Trust II", "Power",
  "SCE Trust IV", "Power",
  "Repsol International Finance BV", "Oil&Gas",
  "Duke Energy Ohio, Inc.", "Power",
  "Energy East Corp.", "Power",
  "US Airways 2013-1 Class A", "Aviation",
  "Burlington Resources Finance Co.", "Oil&Gas",
  "American Airlines 1991-B Pass Through Trust", "Aviation",
  "Rio Tinto Finance (USA) Plc", "Steel",
  "Methanex Corp.", "Oil&Gas",
  "Petrobras Argentina SA", "Power",
  "Comstock Escrow Corp.", "Oil&Gas",
  "Volkswagen Leasing GmbH", "Other",
  "Iberdrola Finanzas SAU", "Power",
  "CRH Finland Services Oyj", "Cement",
  "Saudi Electricity Global SUKUK Co.", "Power",
  "Zim Shipping Ltd.", "Shipping",
  "UtiliCorp United, Inc. /Old/", "Power", # nolint: nonportable_path_linter
  "Holcim Sterling Finance (Netherlands) BV", "Cement",
  "Toyota Leasing (Thailand) Co., Ltd.", "Other",
  "CNOOC Finance (2013) Ltd.", "Oil&Gas",
  "Usiminas International SARL", "Steel",
  "Texaco Capital, Inc.", "Oil&Gas",
  "Holcim Finance US LLC", "Cement",
  "Holcim Overseas Finance Ltd.", "Cement",
  "Northern Powergrid Holdings Co.", "Power",
  "Polar Tankers, Inc.", "Shipping",
  "US Airways Pass Thru 2012-2", "Aviation",
  "Volkswagen Leasing SA de CV", "Other",
  "Wintershall Dea Finance BV", "Oil&Gas",
  "China Southern Power Grid International Finance BVI Co., Ltd.", "Power",
  "United Airlines Pass Through Trust 1994-AA2", "Aviation",
  "Bruce Mansfield Plant Unit 1", "Power",
  "Southwest Airlines Pass Through Certificates Series 2007-1", "Aviation",
  "FCE Bank Plc", "Other",
  "Holcim Helvetia Finance Ltd.", "Cement",
  "HeidelbergCement Finance Luxembourg SA", "Cement",
  "Votorantim Cimentos SA", "Cement",
  "Geo Coal International Pte Ltd.", "Coal",
  "CNOOC  Finance (2014) ULC", "Oil&Gas",
  "Sinopec Capital (2013) Ltd.", "Oil&Gas",
  "Toyota Financial Services (South Africa) (Pty) Ltd.", "Other",
  "HKN Energy Ltd.", "Oil&Gas",
  "Rio Tinto Finance Plc", "Steel",
  "Foresight Energy LLC", "Coal",
  "Air Canada 2015-2 Pass Through Trust", "Aviation",
  "Dolphin Subsidiary II, Inc.", "Power",
  "Medjool Ltd.", "Aviation",
  "Rushydro Capital Markets DAC", "Power",
  "PACCAR Financial Europe BV", "Other",
  "American Trans Air Pass Through Trusts", "Aviation",
  "CNPC General Capital Ltd.", "Oil&Gas",
  "Emera US Finance LP", "Power",
  "Rio Tinto Finance (USA) Ltd.", "Steel",
  "American Airlines 2015-1 Pass Through Trust", "Aviation",
  "Infraestructura Energetica Nova SAB de CV", "Power",
  "Geely Finance (Hong Kong) Ltd.", "Other",
  "SK Innovation Co., Ltd.", "Oil&Gas",
  "EvrazHolding Finance LLC", "Steel",
  "C8 Capital (SPV) Ltd.", "Cement",
  "Soechi Capital Pte Ltd.", "Shipping",
  "United Airlines 2016-2 Class B Pass Thru Trust", "Aviation",
  "American Airlines 2013-2 Pass Through Trust", "Aviation",
  "Mercedes-Benz Financial Services Italia SpA", "Other",
  "Korea Resources Corp. (South Korea)", "Coal",
  "American Airlines 2014-1 Class A Pass Through Trust", "Aviation",
  "Ethiopian Leasing 2012 LLC", "Aviation",
  "Continental Airlines Pass Through Certificates Ser 2012-1", "Aviation",
  "PECO Energy Capital Trust III", "Power",
  "Indian Oil Corp. Ltd.", "Oil&Gas",
  "APLP Holdings LP", "Power",
  "Watercraft Capital SA", "Power",
  "Votorantim Cimentos N/NE SA", "Cement", # nolint: nonportable_path_linter
  "Naftogaz of Ukraine NJSC", "Oil&Gas",
  "Sinosing Services Pte Ltd.", "Power",
  "Duke Energy Florida Project Finance LLC", "Power",
  "Yorkshire Power Finance Ltd.", "Power",
  "Security Capital Group, Inc.", "Power",
  "Continental Airlines Pass Through Certificates Series 2007-1", "Aviation",
  "UHI Capital Ltd.", "Power",
  "TOTE Maritime Alaska, Inc.", "Shipping",
  "CRH Finance Germany GmbH", "Cement",
  "Banco BTG Pactual SA", "Other",
  "CRH Finance Switzerland AG", "Cement",
  "American Airlines 2015-2 Pass Through Trust", "Aviation",
  "Majapahit Holding BV", "Power",
  "AES El Salvador Trust II", "Power",
  "Apache Finance Canada LLC", "Oil&Gas",
  "Adarna Energy Corp.", "Oil&Gas",
  "Air Canada 2015-1 Pass Through Trust", "Aviation",
  "American Airlines 2016-3B Pass Through Trust", "Aviation",
  "CNOOC Finance (2015) U.S.A. LLC", "Oil&Gas",
  "DPL Capital Trust II", "Power",
  "PACCAR Financial M√©xico SA de CV", "Other",
  "United Airlines Pass Through Trust Series 2014-2", "Aviation",
  "USX Corp. /Old/", "Oil&Gas", # nolint: nonportable_path_linter
  "Alaska Airlines 2020-1 Pass Thru Trust", "Aviation",
  "ENI Coordination Center SA", "Oil&Gas",
  "Oil India Ltd.", "Oil&Gas",
  "Bosphorus 2015 LLC", "Aviation",
  "American Airlines 2017-2B Pass Through Trust", "Aviation",
  "BlueScope Finance (Americas) LLC", "Steel",
  "C5 Capital (SPV) Ltd.", "Cement",
  "Sasol Financing USA LLC", "Coal",
  "Peabody Securities Finance Corp.", "Coal",
  "PECO Energy Capital Trust IV", "Power",
  "Jaiprakash Associates Ltd.", "Cement",
  "TMK Capital SA", "Steel",
  "China Huadian Overseas Development 2018 Ltd.", "Power",
  "Sinopec Century Bright Capital Investment Ltd.", "Oil&Gas",
  "Eterna Capital Pte Ltd.", "Coal",
  "Kraftwerke Oberhasli AG", "Power",
  "Continental Airlines Pass Through Certificates Series 2010-1", "Aviation",
  "MP Environmental Funding Series A", "Power",
  "Steel Funding DAC", "Steel",
  "GE Capital Canada Funding Co.", "Power",
  "American Airlines 2013-1 Pass Through Trust", "Aviation",
  "COSCO Finance (2011) Ltd.", "Shipping",
  "CRH Finance DAC", "Cement",
  "Air Canada 2017-1 Pass Through Trust", "Aviation",
  "Jisco SR Pearl Ltd.", "Steel",
  "American Airlines 2013-1B Pass Through Trust", "Aviation",
  "Algoma Acquisition Corp.", "Steel",
  "Saudi Electricity Global Sukuk Co. - 2", "Power",
  "US Airways Pass Through Certificates Series 2011-1", "Aviation",
  "American Airlines 2016-2 Pass Through Trust", "Aviation",
  "US Airways Pass Through 2010-1", "Aviation",
  "China Shenhua Overseas Capital Co., Ltd.", "Coal",
  "CSN Inova Ventures", "Steel",
  "Rosneft International Finance Ltd.", "Oil&Gas",
  "Iberdrola Finance Ireland DAC", "Power",
  "Fiat Chrysler Finance Europe SA", "Other",
  "American Airlines 2011-1 Pass Through Trust", "Aviation",
  "PE Environmental Funding Series B", "Power",
  "American Airlines 2017-2 Pass Through Trust", "Aviation",
  "WMC Finance (USA) Ltd.", "Coal",
  "Reliance Jio Infocomm Ltd.", "Oil&Gas",
  "SPD Finance UK Plc", "Power",
  "Magnolia Oil & Gas Operating LLC", "Oil&Gas",
  "HollyFrontier Corp.", "Oil&Gas",
  "Borger Energy Associates LP", "Power",
  "United Airlines Pass Through Trust Series 2018-1", "Aviation",
  "SPIC 2016 US Dollar Bond Co. Ltd.", "Power",
  "CRH SMW Finance DAC", "Cement",
  "C10-EUR Capital (SPV) Ltd.", "Cement",
  "Continental Airlines Pass Through Certificates Ser 2005-ERJ1", "Aviation",
  "TerraForm Global Operating LLC", "Power",
  "SPIC 2018 USD Senior Perpetual Bond Co. Ltd.", "Power",
  "CRH Funding BV", "Cement",
  "Franchise Finance Corp. of America", "Power",
  "Conoco Funding Co.", "Oil&Gas",
  "SP Group Treasury Pte Ltd.", "Power",
  "SCE Trust VI", "Power",
  "NIE Finance Plc", "Power",
  "US Airways Pass Thru 2012-1", "Aviation",
  "AES Eastern Energy 1999-1", "Power",
  "BMW Finance SNC", "Other",
  "Ratio Oil Explorations Finance Ltd.", "Oil&Gas",
  "BLT Finance BV", "Shipping",
  "SCE Trust III", "Power",
  "China Huadian Overseas Development Management Co., Ltd.", "Power",
  "Sinopec Capital Co., Ltd.", "Oil&Gas",
  "Northwest Airlines 2001-1 Pass Through Trusts", "Aviation",
  "Sasol Financing International Ltd.", "Coal",
  "Fortis, Inc. (United States)", "Power",
  "MP Environmental Funding Series B", "Power",
  "ENEOS Holdings, Inc.", "Oil&Gas",
  "Kondor Finance Plc", "Oil&Gas",
  "Carpenter Technology Corp.", "Steel",
  "Constellation Generation Ltd.", "Power",
  "C10 Capital (SPV) Ltd.", "Cement",
  "Hawaiian Airlines 2013-1 Pass Through Trust", "Aviation",
  "US Airways Pass Thru 2001-1", "Aviation",
  "Vectren Utility Holdings, Inc.", "Power",
  "Cathay Pacific MTN Financing Ltd.", "Aviation",
  "US Airways, Inc. Pass Through Certificates Series 2010-1", "Aviation",
  "AES Panama Generation Holdings SRL", "Power",
  "Globalsol Villanueva 1 SA", "Power",
  "Santos Finance Ltd.", "Oil&Gas",
  "Deutsche Bank M√©xico SA, Instituci√≥n de Banca M√∫ltiple", "Aviation",
  "ConocoPhillips Canada Funding Co. II", "Oil&Gas",
  "Washington Natural Gas Co.", "Power",
  "Services Industriels de Gen√®ve", "Power",
  "United Airlines Pass Through Trust Series 2016-1", "Aviation",
  "Continental Airlines Series 2000-2", "Aviation",
  "Northern Indiana Public Service Co. LLC", "Power",
  "General Electric Capital Services, Inc.", "Power",
  "Dominion Resources Capital Trust III", "Power",
  "Noranda, Inc.", "Coal",
  "Uni√≥n Fenosa Preferentes SA", "Power",
  "Hainan Airlines (Hong Kong) Co., Ltd.", "Aviation",
  "Equatorial Transmissora 3 SPE SA", "Power",
  "Spirit Airlines Pass Through Trust Certificates Series 2015-1", "Aviation",
  "United Airlines Pass Through Trust Series 2013-1", "Aviation",
  "Vattenfall Treasury AB", "Power",
  "United Air Lines 2007-1A Pass Through", "Aviation",
  "SPIC MTN Co. Ltd.", "Power",
  "Tianrui Group Co., Ltd.", "Cement",
  "IL&FS Tamil Nadu Power Co. Ltd.", "Power",
  "Naturgy Capital Markets SA", "Power",
  "BPRL International Singapore Pte Ltd.", "Oil&Gas",
  "Njord Gas Infrastructure AS", "Oil&Gas",
  "Crown Energy AB", "Oil&Gas",
  "BBMG Corp.", "Cement",
  "Petrol dd Ljubljana", "Oil&Gas",
  "RH Petrogas Ltd.", "Oil&Gas",
  "Nordic American Tankers Ltd.", "Shipping",
  "EP Infrastructure as", "Power",
  "CEMEX Latam Holdings SA", "Cement",
  "Jayaswal NECO Industries Ltd.", "Steel",
  "Kesoram Industries Ltd.", "Cement",
  "Essar Shipping Ltd.", "Shipping",
  "Eaton Corp. Plc", "Power",
  "Bonheur ASA", "Shipping",
  "DMCI Holdings, Inc.", "Power",
  "Tatneft PJSC", "Oil&Gas",
  "Siemens AG", "Power",
  "Usha Martin Ltd.", "Steel",
  "Rio Tinto Plc", "Steel",
  "Liaoning SG Automotive Group Co., Ltd.", "Other",
  "Carnegie Clean Energy Ltd.", "Power",
  "Zotye Automobile Co., Ltd.", "Other",
  "Schlumberger NV", "Oil&Gas",
  "PEDEVCO Corp.", "Oil&Gas",
  "Rey Resources Ltd.", "Oil&Gas",
  "Clontarf Energy Plc", "Oil&Gas",
  "Hod - Assaf Industries Ltd.", "Steel",
  "Altona Rare Earths Plc", "Coal",
  "Intra Energy Corp. Ltd.", "Coal",
  "Corsa Coal Corp.", "Coal",
  "Iino Kaiun Kaisha, Ltd.", "Shipping",
  "Hitachi Metals, Ltd.", "Steel",
  "Ningbo Marine Co., Ltd.", "Shipping",
  "PetroNeft Resources Plc", "Oil&Gas",
  "BW LPG Ltd.", "Shipping",
  "Ann Joo Resources Bhd.", "Steel",
  "Rio Tinto Ltd.", "Steel",
  "Dialog Group Bhd.", "Oil&Gas",
  "Erin Energy Corp.", "Oil&Gas",
  "Huadian Power International Corp. Ltd.", "Power",
  "Havilafjord AS", "Shipping",
  "Lapidoth Capital Ltd.", "Oil&Gas",
  "Aditya Birla Nuvo Ltd.", "Cement",
  "E.A. Technique (M) Bhd.", "Shipping",
  "New Age Exploration Ltd.", "Coal",
  "Independent Petroleum Group KSCP", "Oil&Gas",
  "Gloria Material Technology Corp.", "Steel",
  "PT Logindo Samudramakmur Tbk", "Shipping",
  "Workhorse Group, Inc.", "Other",
  "Anglo American Plc", "Coal",
  "SK Inc.", "Oil&Gas",
  "Kohinoor Textile Mills Ltd.", "Cement",
  "Ningbo Sanxing Medical Electric Co., Ltd.", "Power",
  "Sparc Technologies Ltd.", "Coal",
  "Tamai Steamship Co., Ltd.", "Shipping",
  "Ameresco, Inc.", "Power",
  "Star Cement Ltd.", "Cement",
  "V-Guard Industries Ltd.", "Power",
  "Guangzhou Development Group, Inc.", "Coal",
  "Hubei Energy Group Co., Ltd.", "Power",
  "Metro Mining Ltd.", "Coal",
  "Grupa LOTOS SA", "Oil&Gas",
  "Hyundai GLOVIS Co., Ltd.", "Shipping",
  "BlueScope Steel Ltd.", "Steel",
  "Siemens Gamesa Renewable Energy SA", "Power",
  "Reach Energy Bhd.", "Oil&Gas",
  "Topy Industries, Ltd.", "Steel",
  "Chang Jiang Shipping Group Phoenix Co., Ltd.", "Shipping",
  "Europa Oil & Gas (Holdings) Plc", "Oil&Gas",
  "PT Berlian Laju Tanker Tbk", "Shipping",
  "Grupo TMM SAB", "Shipping",
  "The Japan Steel Works Ltd.", "Steel",
  "Xinyu Iron & Steel Co., Ltd.", "Steel",
  "Mitsui Matsushima Holdings Co., Ltd.", "Coal",
  "Kibo Energy Plc", "Power",
  "Anhui Jianghuai Automobile Group Corp. Ltd.", "Other",
  "Wuling Motors Holdings Ltd.", "Other",
  "Grupo Argos SA", "Cement",
  "New Concept Energy, Inc.", "Oil&Gas",
  "Dalmia Bharat Ltd.", "Cement",
  "EuroSite Power, Inc.", "Power",
  "Oando Plc", "Oil&Gas",
  "Tlou Energy Ltd.", "Oil&Gas"
)
