#' Manually mantained PACTA Sector override mapping
#' Use the `entity_proper_name` to match the company name in the FactSet
#' database.
#' For each company, the `pacta_sector` column contains the sector that
#' should be used in the PACTA analysis.
#' The `entity_id_md5` column contains the md5 hash of the entity_id, which
#' is used to disambiguate the company in the FactSet database in the case of
#' multiple companies with the same `entity_proper_name`.
#'
#' To generate values for the `entity_id_md5` column, use the following code:
#' `digest::digest(<entity_id>, algo = "md5", serialize = FALSE)`'.
#'
#' @keywords internal

pacta_sector_override_mapping <- tibble::tribble(
  ~entity_proper_name, ~pacta_sector, ~entity_id_md5,
  "ABJA Investment Co. Pte Ltd.", "Steel", NA,
  "AES Eastern Energy 1999-1", "Power", NA,
  "AES El Salvador Trust II", "Power", NA,
  "AES Espa\u00f1a BV", "Power", NA,
  "AES Panama Generation Holdings SRL", "Power", NA,
  "APLP Holdings LP", "Power", NA,
  "Abu Dhabi National Energy Co. PJSC", "Power", NA,
  "Adarna Energy Corp.", "Oil&Gas", NA,
  "Aditya Birla Nuvo Ltd.", "Cement", NA,
  "Air Canada 2013-1 Pass Through Trust", "Aviation", NA,
  "Air Canada 2015-1 Pass Through Trust", "Aviation", NA,
  "Air Canada 2015-2 Pass Through Trust", "Aviation", NA,
  "Air Canada 2017-1 Pass Through Trust", "Aviation", NA,
  "Alaska Airlines 2020-1 Pass Thru Trust", "Aviation", NA,
  "Algoma Acquisition Corp.", "Steel", NA,
  "Alliant Energy Finance LLC", "Power", NA,
  "Altona Rare Earths Plc", "Coal", NA,
  "Ameresco, Inc.", "Power", NA,
  "America West Airlines 2001-1", "Aviation", NA,
  "American Airlines 1991-B Pass Through Trust", "Aviation", NA,
  "American Airlines 2001-1 Pass ThroughTrust", "Aviation", NA,
  "American Airlines 2011-1 Pass Through Trust", "Aviation", NA,
  "American Airlines 2011-2 Pass Through Trust", "Aviation", NA,
  "American Airlines 2013-1 Pass Through Trust", "Aviation", NA,
  "American Airlines 2013-1A Pass Through Trust", "Aviation", NA,
  "American Airlines 2013-1B Pass Through Trust", "Aviation", NA,
  "American Airlines 2013-2 Pass Through Trust", "Aviation", NA,
  "American Airlines 2014-1 Class A Pass Through Trust", "Aviation", NA,
  "American Airlines 2015-1 Pass Through Trust", "Aviation", NA,
  "American Airlines 2015-2 Pass Through Trust", "Aviation", NA,
  "American Airlines 2016-2 Pass Through Trust", "Aviation", NA,
  "American Airlines 2016-2B Pass Through Trust", "Aviation", NA,
  "American Airlines 2016-3 Pass Through Trust", "Aviation", NA,
  "American Airlines 2016-3B Pass Through Trust", "Aviation", NA,
  "American Airlines 2017-1 Pass Through Trust", "Aviation", NA,
  "American Airlines 2017-2 Pass Through Trust", "Aviation", NA,
  "American Airlines 2017-2B Pass Through Trust", "Aviation", NA,
  "American Airlines 2019-1 Through Trust", "Aviation", NA,
  "American Honda Finance Corp.", "Other", NA,
  "American President Cos. Ltd.", "Shipping", NA,
  "American Trans Air Pass Through Trusts", "Aviation", NA,
  "Anadarko Finance Co.", "Oil&Gas", NA,
  "Anglo American Plc", "Coal", NA,
  "Anhui Jianghuai Automobile Group Corp. Ltd.", "Other", NA,
  "Ann Joo Resources Bhd.", "Steel", NA,
  "Apache Finance Canada LLC", "Oil&Gas", NA,
  "BBMG Corp.", "Cement", NA,
  "BG Energy Capital Plc", "Oil&Gas", NA,
  "BHP Billiton Finance (USA) Ltd.", "Coal", NA,
  "BHP Billiton Finance Ltd.", "Coal", NA,
  "BLT Finance BV", "Shipping", NA,
  "BMW Canada, Inc.", "Other", NA,
  "BMW Finance NV", "Other", NA,
  "BMW Finance SNC", "Other", NA,
  "BMW International Investment BV", "Other", NA,
  "BMW US Capital LLC", "Other", NA,
  "BP Capital Markets America, Inc.", "Oil&Gas", NA,
  "BP Capital Markets Plc", "Oil&Gas", NA,
  "BPRL International Singapore Pte Ltd.", "Oil&Gas", NA,
  "BW LPG Ltd.", "Shipping", NA,
  "Baltimore Gas & Electric Co.", "Power", NA,
  "Banco BTG Pactual SA (Cayman Branch)", "Oil&Gas", NA,
  "Banco BTG Pactual SA", "Other", NA,
  "Banque PSA Finance SA", "Other", NA,
  "Bharat Petroleum Corp. Ltd.", "Oil&Gas", NA,
  "BlueScope Finance (Americas) LLC", "Steel", NA,
  "BlueScope Steel Ltd.", "Steel", NA,
  "Bonheur ASA", "Shipping", NA,
  "Borger Energy Associates LP", "Power", NA,
  "Bosphorus 2015 LLC", "Aviation", NA,
  "British Airways Pass Through Trust 2018-1AA", "Aviation", NA,
  "British Airways Pass Through Trust 2019-1", "Aviation", NA,
  "British Airways Pass Through Trust Series 2013-1", "Aviation", NA,
  "Bruce Mansfield Plant Unit 1", "Power", NA,
  "Burlington Resources Finance Co.", "Oil&Gas", NA,
  "C10 Capital (SPV) Ltd.", "Cement", NA,
  "C10-EUR Capital (SPV) Ltd.", "Cement", NA,
  "C5 Capital (SPV) Ltd.", "Cement", NA,
  "C8 Capital (SPV) Ltd.", "Cement", NA,
  "CEMEX Latam Holdings SA", "Cement", NA,
  "CGNPC International Ltd.", "Power", NA,
  "CITIC Ltd.", "Power", NA,
  "CLP Power Hong Kong Financing Ltd.", "Power", NA,
  "CNOOC Curtis Funding No. 1 Pty Ltd.", "Oil&Gas", NA,
  "CNOOC Finance (2003) Ltd.", "Oil&Gas", NA,
  "CNOOC Finance (2011) Ltd.", "Oil&Gas", NA,
  "CNOOC Finance (2012) Ltd.", "Oil&Gas", NA,
  "CNOOC Finance (2013) Ltd.", "Oil&Gas", NA,
  "CNOOC Finance (2014) ULC", "Oil&Gas", NA,
  "CNOOC Finance (2015) U.S.A. LLC", "Oil&Gas", NA,
  "CNPC (HK) Overseas Capital Ltd.", "Oil&Gas", NA,
  "CNPC General Capital Ltd.", "Oil&Gas", NA,
  "CNX Resources Corp.", "Oil&Gas", NA,
  "COSCO Finance (2011) Ltd.", "Shipping", NA,
  "CRH America Finance, Inc.", "Cement", NA,
  "CRH Finance DAC", "Cement", NA,
  "CRH Finance Germany GmbH", "Cement", NA,
  "CRH Finance Switzerland AG", "Cement", NA,
  "CRH Finance UK Plc", "Cement", NA,
  "CRH Finland Services Oyj", "Cement", NA,
  "CRH Funding BV", "Cement", NA,
  "CRH SMW Finance DAC", "Cement", NA,
  "CSN Inova Ventures", "Steel", NA,
  "CSN Islands XII Corp.", "Steel", NA,
  "CalEnergy Co., Inc.", "Power", NA,
  "Canadian Utilities Ltd.", "Power", NA,
  "Capex SA", "Power", NA,
  "Carnegie Clean Energy Ltd.", "Power", NA,
  "Carpenter Technology Corp.", "Steel", NA,
  "Cathay Pacific MTN Financing Ltd.", "Aviation", NA,
  "China Clean Energy Development Ltd.", "Power", NA,
  "China Huadian Overseas Development 2018 Ltd.", "Power", NA,
  "China Huadian Overseas Development Management Co., Ltd.", "Power", NA,
  "China Huaneng Group Treasury Management (Hong Kong) Ltd.", "Power", "94861e52fe0e1b3cc7a86d14c71d643b", # nolint: line_length_linter
  "China Petrochemical Corp.", "Oil&Gas", NA,
  "China Shenhua Overseas Capital Co., Ltd.", "Coal", NA,
  "China Southern Power Grid Co., Ltd.", "Power", NA,
  "China Southern Power Grid International Finance BVI Co., Ltd.", "Power", NA,
  "Chongqing Energy Investment Group Co., Ltd.", "Coal", NA,
  "City of Dallas (Texas)", "Other", NA,
  "Clontarf Energy Plc", "Oil&Gas", NA,
  "Cnooc Finance (2015) Australia Pty Ltd.", "Oil&Gas", NA,
  "Companhia Brasileira de Alum\u00ednio", "Steel", NA,
  "Comstock Escrow Corp.", "Oil&Gas", NA,
  "Conoco Funding Co.", "Oil&Gas", NA,
  "Conoco, Inc.", "Oil&Gas", NA,
  "ConocoPhillips Canada Funding Co. II", "Oil&Gas", NA,
  "Constellation Generation Ltd.", "Power", NA,
  "Continental Airlines Pass Through Certificates Ser 2005-ERJ1", "Aviation", NA, #nolint: line_length_linter
  "Continental Airlines Pass Through Certificates Ser 2012-1", "Aviation", NA,
  "Continental Airlines Pass Through Certificates Ser 2012-2", "Aviation", NA,
  "Continental Airlines Pass Through Certificates Series 2001-1", "Aviation", NA, #nolint: line_length_linter
  "Continental Airlines Pass Through Certificates Series 2007-1", "Aviation", NA, #nolint: line_length_linter
  "Continental Airlines Pass Through Certificates Series 2010-1", "Aviation", NA, #nolint: line_length_linter
  "Continental Airlines Series 2000-2", "Aviation", NA,
  "Corsa Coal Corp.", "Coal", NA,
  "County of Dallas (Texas)", "Aviation", NA,
  "Crown Energy AB", "Oil&Gas", NA,
  "DMCI Holdings, Inc.", "Power", NA,
  "DPL Capital Trust II", "Power", NA,
  "Dalmia Bharat Ltd.", "Cement", NA,
  "Delta Air Lines 2002-1", "Aviation", NA,
  "Delta Air Lines Pass Through 2007-1", "Aviation", NA,
  "Deutsche Bank M\u00e9xico SA, Instituci\u00f3n de Banca M\u00faltiple", "Aviation", NA, # nolint: line_length_linter
  "Devon Financing Corp. ULC", "Oil&Gas", NA,
  "Dialog Group Bhd.", "Oil&Gas", NA,
  "Dolphin Subsidiary II, Inc.", "Power", NA,
  "Dominion Resources Capital Trust III", "Power", NA,
  "Duke Energy Florida Project Finance LLC", "Power", NA,
  "Duke Energy Ohio, Inc.", "Power", NA,
  "E.A. Technique (M) Bhd.", "Shipping", NA,
  "E.ON International Finance BV", "Power", NA,
  "EDP Finance BV", "Power", NA,
  "ENBW International Finance BV", "Power", NA,
  "ENEL Finance International NV", "Power", NA,
  "ENEL Finance International SA", "Power", NA,
  "ENEOS Holdings, Inc.", "Oil&Gas", NA,
  "ENI Coordination Center SA", "Oil&Gas", NA,
  "EP Infrastructure as", "Power", NA,
  "ESB Finance DAC", "Power", NA,
  "Eaton Corp. Plc", "Power", NA,
  "Emera US Finance LP", "Power", NA,
  "Emerson Electric Co.", "Power", NA,
  "Empresas P\u00fablicas de Medell\u00edn ESP", "Power", NA,
  "Energa Finance AB", "Power", NA,
  "Energy East Corp.", "Power", NA,
  "Equatorial Transmissora 3 SPE SA", "Power", NA,
  "Equatorial Transmissora 8 Spe SA", "Power", NA,
  "Erin Energy Corp.", "Oil&Gas", NA,
  "Essar Shipping Ltd.", "Shipping", NA,
  "Eterna Capital Pte Ltd.", "Coal", NA,
  "Ethiopian Leasing 2012 LLC", "Aviation", NA,
  "EuroSite Power, Inc.", "Power", NA,
  "Europa Oil & Gas (Holdings) Plc", "Oil&Gas", NA,
  "EvrazHolding Finance LLC", "Steel", NA,
  "FCE Bank Plc", "Other", NA,
  "Fiat Chrysler Finance Europe SA", "Other", NA,
  "Ford Credit Canada Co.", "Other", NA,
  "Ford Holdings, Inc.", "Other", NA,
  "Ford Motor Credit Co. LLC", "Other", NA,
  "Foresight Energy LLC", "Coal", NA,
  "Fortis, Inc. (United States)", "Power", NA,
  "Franchise Finance Corp. of America", "Power", NA,
  "GE Capital Australia Funding Pty Ltd.", "Power", NA,
  "GE Capital Canada Funding Co.", "Power", NA,
  "GE Capital European Funding Unlimited Co.", "Power", NA,
  "GE Capital Funding LLC", "Power", NA,
  "GE Capital International Funding Company Unlimited Co.", "Power", NA,
  "GE Capital UK Funding Unlimited Co.", "Power", NA,
  "GIE PSA Tresorerie", "Other", NA,
  "GMF Floorplan Owner Revolving Trust 2018-4 Ltd.", "Other", NA,
  "GOL Finance Ltd.", "Aviation", NA,
  "GPN Capital SA", "Oil&Gas", NA,
  "GTL Trade Finance, Inc.", "Steel", NA,
  "Gaz Capital SA", "Oil&Gas", NA,
  "Gaz Finance Plc", "Oil&Gas", NA,
  "Geely Finance (Hong Kong) Ltd.", "Other", NA,
  "Genel Energy Finance Plc", "Oil&Gas", NA,
  "General Electric Capital Corp.", "Power", NA,
  "General Electric Capital Services, Inc.", "Power", NA,
  "General Motors Financial Co., Inc.", "Other", NA,
  "General Motors Financial of Canada Ltd.", "Other", NA,
  "Genneia SA", "Power", NA,
  "Geo Coal International Pte Ltd.", "Coal", NA,
  "Glencore Finance (Canada) ltd.", "Coal", NA,
  "Glencore Finance (Europe) Ltd.", "Coal", NA,
  "Glencore Funding LLC", "Coal", NA,
  "Globalsol Villanueva 1 SA", "Power", NA,
  "Gloria Material Technology Corp.", "Steel", NA,
  "Government of Gabon", "Other", NA,
  "Grupa LOTOS SA", "Oil&Gas", NA,
  "Grupo Argos SA", "Cement", NA,
  "Grupo TMM SAB", "Shipping", NA,
  "Guangzhou Development Group, Inc.", "Coal", NA,
  "Gusap III LP", "Steel", NA,
  "HKN Energy Ltd.", "Oil&Gas", NA,
  "Hainan Airlines (Hong Kong) Co., Ltd.", "Aviation", NA,
  "Havilafjord AS", "Shipping", NA,
  "Hawaiian Airlines 2013-1 Pass Through Trust", "Aviation", NA,
  "Heidelberg Materials Finance Luxembourg SA", "Cement", NA,
  "Hilcorp Energy I LP", "Oil&Gas", NA,
  "Hod - Assaf Industries Ltd.", "Steel", NA,
  "Holcim Capital Corp. Ltd.", "Cement", NA,
  "Holcim Finance (Luxembourg) SA", "Cement", NA,
  "Holcim Finance US LLC", "Cement", NA,
  "Holcim Helvetia Finance Ltd.", "Cement", NA,
  "Holcim Overseas Finance Ltd.", "Cement", NA,
  "Holcim Sterling Finance (Netherlands) BV", "Cement", NA,
  "HollyFrontier Corp.", "Oil&Gas", NA,
  "Honda Canada Finance, Inc.", "Other", NA,
  "Hrvatska Elektroprivreda dd", "Power", NA,
  "Huadian Power International Corp. Ltd.", "Power", NA,
  "Hubei Energy Group Co., Ltd.", "Power", NA,
  "Hyundai GLOVIS Co., Ltd.", "Shipping", NA,
  "IL&FS Tamil Nadu Power Co. Ltd.", "Power", NA,
  "Iberdrola Finance Ireland DAC", "Power", NA,
  "Iberdrola Finanzas SAU", "Power", NA,
  "Iino Kaiun Kaisha, Ltd.", "Shipping", NA,
  "Independent Petroleum Group KSCP", "Oil&Gas", NA,
  "Indian Oil Corp. Ltd.", "Oil&Gas", NA,
  "Indika Energy Capital III Pte Ltd.", "Coal", NA,
  "Infraestructura Energetica Nova SAB de CV", "Power", NA,
  "Instituto Costarricense de Electricidad", "Power", NA,
  "Intra Energy Corp. Ltd.", "Coal", NA,
  "Jaiprakash Associates Ltd.", "Cement", NA,
  "Jayaswal NECO Industries Ltd.", "Steel", NA,
  "Jisco SR Pearl Ltd.", "Steel", NA,
  "Kesoram Industries Ltd.", "Cement", NA,
  "KeySpan Corp.", "Power", NA,
  "Kibo Energy Plc", "Power", NA,
  "Kimanis Power Sdn. Bhd.", "Power", NA,
  "Kohinoor Textile Mills Ltd.", "Cement", NA,
  "Kondor Finance Plc", "Oil&Gas", NA,
  "Korea Resources Corp. (South Korea)", "Coal", NA,
  "Kraftwerke Oberhasli AG", "Power", NA,
  "LATAM Finance Ltd.", "Aviation", NA,
  "LUKOIL International Finance BV", "Oil&Gas", NA,
  "LUKOIL Securities BV", "Oil&Gas", NA,
  "Lapidoth Capital Ltd.", "Oil&Gas", NA,
  "Liaoning SG Automotive Group Co., Ltd.", "Other", NA,
  "MMK International Capital DAC", "Steel", NA,
  "MP Environmental Funding Series A", "Power", NA,
  "MP Environmental Funding Series B", "Power", NA,
  "Magnolia Oil & Gas Operating LLC", "Oil&Gas", NA,
  "Majapahit Holding BV", "Power", NA,
  "Manjung Island Energy Bhd.", "Power", NA,
  "Medjool Ltd.", "Aviation", NA,
  "Mercedes-Benz Australia/Pacific Pty Ltd.", "Other", NA, # nolint: nonportable_path_linter
  "Mercedes-Benz Finance Canada, Inc.", "Other", NA,
  "Mercedes-Benz Finance KK", "Other", NA,
  "Mercedes-Benz Finance North America LLC", "Other", NA,
  "Mercedes-Benz Financial Services Italia SpA", "Other", NA,
  "Mercedes-Benz International Finance BV", "Other", NA,
  "Methanex Corp.", "Oil&Gas", NA,
  "Metro Mining Ltd.", "Coal", NA,
  "Mitsui Matsushima Holdings Co., Ltd.", "Coal", NA,
  "NAS Pass Through Trust 2016-1A", "Aviation", NA,
  "NAS Pass Through Trust 2016-1B", "Aviation", NA,
  "NIE Finance Plc", "Power", NA,
  "Nacional Financiera SNC", "Aviation", NA,
  "Naftogaz of Ukraine NJSC", "Oil&Gas", NA,
  "National Rural Utilities Cooperative Finance Corp.", "Power", NA,
  "Naturgy Capital Markets SA", "Power", NA,
  "Naturgy Finance BV", "Power", NA,
  "New Age Exploration Ltd.", "Coal", NA,
  "New Concept Energy, Inc.", "Oil&Gas", NA,
  "NextEra Energy Capital Holdings, Inc.", "Power", NA,
  "Niagara Mohawk Power Corp.", "Power", NA,
  "Ningbo Marine Co., Ltd.", "Shipping", NA,
  "Ningbo Sanxing Medical Electric Co., Ltd.", "Power", NA,
  "Nissan Motor Acceptance Co.", "Other", NA,
  "Njord Gas Infrastructure AS", "Oil&Gas", NA,
  "Noranda, Inc.", "Coal", NA,
  "Nordic American Tankers Ltd.", "Shipping", NA,
  "Northern Electric Finance Plc", "Power", NA,
  "Northern Indiana Public Service Co. LLC", "Power", NA,
  "Northern Powergrid Holdings Co.", "Power", NA,
  "Northwest Airlines 2001-1 Pass Through Trusts", "Aviation", NA,
  "Northwest Airlines Pass Through Trusts (NWA) 2002-1", "Aviation", NA,
  "Novatek Finance DAC", "Oil&Gas", NA,
  "ORLEN SA", "Oil&Gas", NA,
  "Oando Plc", "Oil&Gas", NA,
  "Oil India Ltd.", "Oil&Gas", NA,
  "Origin Energy Finance Ltd.", "Power", NA,
  "Outokumpu Oyj", "Steel", NA,
  "PACCAR Financial Corp.", "Other", NA,
  "PACCAR Financial Europe BV", "Other", NA,
  "PACCAR Financial M\u00e9xico SA de CV", "Other", NA,
  "PE Environmental Funding LLC", "Power", NA,
  "PE Environmental Funding Series B", "Power", NA,
  "PECO Energy Capital Trust III", "Power", NA,
  "PECO Energy Capital Trust IV", "Power", NA,
  "PEDEVCO Corp.", "Oil&Gas", NA,
  "PETRONAS Capital Ltd.", "Oil&Gas", NA,
  "PPL Capital Funding, Inc.", "Power", NA,
  "PT Berlian Laju Tanker Tbk", "Shipping", NA,
  "PT Logindo Samudramakmur Tbk", "Shipping", NA,
  "Peabody Securities Finance Corp.", "Coal", NA,
  "Pemex Project Funding Master Trust", "Oil&Gas", NA,
  "PetroNeft Resources Plc", "Oil&Gas", NA,
  "Petrobras Argentina SA", "Power", NA,
  "Petrobras Global Finance BV", "Oil&Gas", NA,
  "Petrol dd Ljubljana", "Oil&Gas", NA,
  "Petroleos Del Peru - Petroperu SA", "Oil&Gas", NA,
  "Phillips Petroleum Co.", "Oil&Gas", NA,
  "Phoenix Shipping (Wuhan) Co., Ltd.", "Shipping", NA,
  "Polar Tankers, Inc.", "Shipping", NA,
  "Proterial Ltd.", "Steel", NA,
  "RCI Banque SA", "Other", NA,
  "RGS (AEGCO) Funding Corp.", "Power", NA,
  "RGS I&M Funding Corp.", "Power", NA,
  "RH Petrogas Ltd.", "Oil&Gas", NA,
  "Ratio Oil Explorations Finance Ltd.", "Oil&Gas", NA,
  "Reach Energy Bhd.", "Oil&Gas", NA,
  "Reliance Industries Ltd.", "Oil&Gas", NA,
  "Reliance Jio Infocomm Ltd.", "Oil&Gas", NA,
  "Repsol International Finance BV", "Oil&Gas", NA,
  "Rey Resources Ltd.", "Oil&Gas", NA,
  "Rio Tinto Finance (USA) Ltd.", "Steel", NA,
  "Rio Tinto Finance (USA) Plc", "Steel", NA,
  "Rio Tinto Finance Plc", "Steel", NA,
  "Rio Tinto Ltd.", "Steel", NA,
  "Rio Tinto Plc", "Steel", NA,
  "Rosneft International Finance Ltd.", "Oil&Gas", NA,
  "Rushydro Capital Markets DAC", "Power", NA,
  "SCE Trust II", "Power", NA,
  "SCE Trust III", "Power", NA,
  "SCE Trust IV", "Power", NA,
  "SCE Trust V", "Power", NA,
  "SCE Trust VI", "Power", NA,
  "SK Innovation Co., Ltd.", "Oil&Gas", NA,
  "SK, Inc.", "Oil&Gas", NA,
  "SLB", "Oil&Gas", NA,
  "SP Group Treasury Pte Ltd.", "Power", NA,
  "SPD Finance UK Plc", "Power", NA,
  "SPIC 2016 US Dollar Bond Co. Ltd.", "Power", NA,
  "SPIC 2018 USD Senior Perpetual Bond Co. Ltd.", "Power", NA,
  "SPIC MTN Co. Ltd.", "Power", NA,
  "San Diego Gas & Electric Co.", "Power", NA,
  "Santos Finance Ltd.", "Oil&Gas", NA,
  "Sasol Financing International Ltd.", "Coal", NA,
  "Sasol Financing USA LLC", "Coal", NA,
  "Saudi Electricity Global Sukuk Co. - 2", "Power", NA,
  "Saudi Electricity Global Sukuk Co. - 3", "Power", NA,
  "Saudi Electricity Global Sukuk Co. - 4", "Power", NA,
  "Saudi Electricity Global Sukuk Co.", "Power", NA,
  "Security Capital Group, Inc.", "Power", NA,
  "Services Industriels de Gen\u00e8ve", "Power", NA,
  "Shell International Finance BV", "Oil&Gas", NA,
  "Siemens AG", "Power", NA,
  "Siemens Gamesa Renewable Energy SA", "Power", NA,
  "Sinopec Capital (2013) Ltd.", "Oil&Gas", NA,
  "Sinopec Capital Co., Ltd.", "Oil&Gas", NA,
  "Sinopec Century Bright Capital Investment Ltd.", "Oil&Gas", NA,
  "Sinopec Group Overseas Development (2012) Ltd.", "Oil&Gas", NA,
  "Sinopec Group Overseas Development (2013) Ltd.", "Oil&Gas", NA,
  "Sinopec Group Overseas Development (2014) Ltd.", "Oil&Gas", NA,
  "Sinopec Group Overseas Development (2016) Ltd.", "Oil&Gas", NA,
  "Sinopec Group Overseas Development (2017) Ltd.", "Oil&Gas", NA,
  "Sinopec Group Overseas Development (2018) Ltd.", "Oil&Gas", NA,
  "Sinopec Group Overseas Development Ltd.", "Oil&Gas", NA,
  "Sinosing Services Pte Ltd.", "Power", NA,
  "Soechi Capital Pte Ltd.", "Shipping", NA,
  "Southwest Airlines Pass Through Certificates Series 2007-1", "Aviation", NA,
  "Sparc Technologies Ltd.", "Coal", NA,
  "Spirit Airlines Pass Through Trust Certificates Series 2015-1", "Aviation", NA, #nolint: line_length_linter
  "St. Marys Cement Inc. (Canada)", "Cement", NA,
  "Star Cement Ltd.", "Cement", NA,
  "State Development & Investment Corp., Ltd.", "Power", NA,
  "State Grid Corp. of China", "Power", NA,
  "State Grid Overseas Investment (2013) Ltd.", "Power", NA,
  "State Grid Overseas Investment (2014) Ltd.", "Power", NA,
  "State of Alaska", "Other", NA,
  "Steel Capital SA", "Steel", NA,
  "Steel Funding DAC", "Steel", NA,
  "Susa Partnership LP", "Power", NA,
  "TMK Capital SA", "Steel", NA,
  "TNB Global Ventures Capital Bhd.", "Power", NA,
  "TNB Western Energy Bhd.", "Power", NA,
  "TOTE Maritime Alaska, Inc.", "Shipping", NA,
  "Tamai Steamship Co., Ltd.", "Shipping", NA,
  "Tatneft PJSC", "Oil&Gas", NA,
  "TerraForm Global Operating LLC", "Power", NA,
  "Texaco Capital, Inc.", "Oil&Gas", NA,
  "The Bank of New York Mellon Corp.", "Other", NA,
  "The Japan Steel Works Ltd.", "Steel", NA,
  "Three Gorges Finance I (Cayman Islands) Ltd.", "Power", NA,
  "Tianrui Group Co., Ltd.", "Cement", NA,
  "Titan Global Finance Plc", "Cement", NA,
  "Tlou Energy Ltd.", "Oil&Gas", NA,
  "Topy Industries, Ltd.", "Steel", NA,
  "Tosco Corp.", "Oil&Gas", "85a3b95ee1db76fc37bcf8ed7430de22",
  "TotalEnergies Capital International SA", "Oil&Gas", NA,
  "Toyota Credit Canada, Inc.", "Other", NA,
  "Toyota Finance Australia Ltd.", "Other", NA,
  "Toyota Finance New Zealand Ltd.", "Other", NA,
  "Toyota Financial Services (South Africa) (Pty) Ltd.", "Other", NA,
  "Toyota Leasing (Thailand) Co. Ltd.", "Other", NA,
  "Toyota Motor Credit Corp.", "Other", NA,
  "Toyota Motor Finance (Netherlands) BV", "Other", NA,
  "UGI Utilities, Inc.", "Power", NA,
  "UHI Capital Ltd.", "Power", NA,
  "US Airways 2013-1 Class A", "Aviation", NA,
  "US Airways 2013-1 Pass Through Trust", "Aviation", NA,
  "US Airways Pass Through Certificates Series 2011-1", "Aviation", NA,
  "US Airways Pass Through Trust 2010-1", "Aviation", NA,
  "US Airways Pass Thru 2001-1", "Aviation", NA,
  "US Airways Pass Thru 2012-1", "Aviation", NA,
  "US Airways Pass Thru 2012-2", "Aviation", NA,
  "US Airways, Inc. Pass Through Certificates Series 2010-1", "Aviation", NA,
  "US Airways, Inc.", "Aviation", NA,
  "USX Corp. /Old/", "Oil&Gas", NA, # nolint: nonportable_path_linter
  "Uni\u00f3n Fenosa Preferentes SA", "Power", NA,
  "United Air Lines 2007-1A Pass Through", "Aviation", NA,
  "United Airlines 1995-A Pass Through Trusts", "Aviation", NA,
  "United Airlines 2016-1 Class B Pass Thru Trust", "Aviation", NA,
  "United Airlines 2016-2 Class B Pass Thru Trust", "Aviation", NA,
  "United Airlines Pass Through Certificate Series 2019-2", "Aviation", NA,
  "United Airlines Pass Through Certificates Series 2019-1", "Aviation", NA,
  "United Airlines Pass Through Trust 1994-AA2", "Aviation", NA,
  "United Airlines Pass Through Trust Series 2013-1", "Aviation", NA,
  "United Airlines Pass Through Trust Series 2014-1", "Aviation", NA,
  "United Airlines Pass Through Trust Series 2014-2", "Aviation", NA,
  "United Airlines Pass Through Trust Series 2015-1", "Aviation", NA,
  "United Airlines Pass Through Trust Series 2016-1", "Aviation", NA,
  "United Airlines Pass Through Trust Series 2016-2", "Aviation", NA,
  "United Airlines Pass Through Trust Series 2018-1", "Aviation", NA,
  "Usha Martin Ltd.", "Steel", NA,
  "Usiminas International SARL", "Steel", NA,
  "UtiliCorp United, Inc. /Old/", "Power", NA, # nolint: nonportable_path_linter
  "V-Guard Industries Ltd.", "Power", NA,
  "VW Credit Canada, Inc.", "Other", NA,
  "Vattenfall Treasury AB", "Power", NA,
  "Vectren Utility Holdings LLC", "Power", NA,
  "Vistra Operations Co. LLC", "Power", NA,
  "Volkswagen Bank GmbH", "Other", NA,
  "Volkswagen Financial Services AG", "Other", NA,
  "Volkswagen Financial Services Australia Pty Ltd.", "Other", NA,
  "Volkswagen Financial Services NV", "Other", NA,
  "Volkswagen Group of America Finance LLC", "Other", NA,
  "Volkswagen International Finance NV", "Other", NA,
  "Volkswagen Leasing GmbH", "Other", NA,
  "Volkswagen Leasing SA de CV", "Other", NA,
  "Volvo Treasury AB", "Other", NA,
  "Votorantim Cimentos N/NE SA", "Cement", NA, # nolint: nonportable_path_linter
  "Votorantim Cimentos SA", "Cement", NA,
  "Voyage Bonds Ltd.", "Steel", NA,
  "WMC Finance (USA) Ltd.", "Coal", NA,
  "WPD Holdings UK", "Power", NA,
  "Washington Natural Gas Co.", "Power", NA,
  "Watercraft Capital SA", "Power", NA,
  "Wintershall Dea Finance BV", "Oil&Gas", NA,
  "Woodside Finance Ltd.", "Oil&Gas", NA,
  "Workhorse Group, Inc.", "Other", NA,
  "Wuling Motors Holdings Ltd.", "Other", NA,
  "Xinyu Iron & Steel Co., Ltd.", "Steel", NA,
  "Yorkshire Power Finance Ltd.", "Power", NA,
  "Zim Shipping Ltd.", "Shipping", NA,
  "Zotye Automobile Co., Ltd.", "Other", NA,
  "innogy Finance BV", "Power", NA
)
