on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron:  '0 0 * * 1,2,3,4,5'

name: Docker

jobs:
  docker:
    name: Docker actions
    uses: RMI-PACTA/actions/.github/workflows/docker.yml@db5322e787ce698dcb77bd922eda2b4bac45f3e8
